### ISSUE TITLE
Not able to select existing Vnet

### ISSUE THREAD

**Issue by BorisChomette** [Azure/migAz#145]
In version 2.4.1.0 I can't associate a NIC to an existing VNET in the selected Resource Group.

**Comment by rsanderson2350** [comment]
Can you provider further details, including steps to reproduce?  Is this an "existing VNET" that you added with the "New Virtual Network Button"?   I screen shot of both the Target Resource Group and Property Panel might also help to see what you are seeing (blur/remove and proprietary names/info from the screen shot).

**Comment by BorisChomette** [comment]
First I create a new Resource Group and VNET in the Azure portal.
After that I select the source subscription and Classic VM I want to migrate.
Then I select the target subscription and change the name of the target resource group to the name of the existing resource group. With previous versions I was able to select the existing VNET to associate the NIC with.

**Comment by BorisChomette** [comment]
How can I add a subnet to a newly created VNET in MigAz?

**Comment by ShamSV** [comment]
The issues is seen in the newer version - 2.4.2.0 as well.
This is happening only when the source and destination have different tenant and subscription.
The option to use the Existing VNet is disabled.

**Comment by rsanderson2350** [comment]
I will do a test now against two different source/target tenants and subscriptions; however, my testing prior to release found this to be working.  The Target Location of the Resource Group must be set prior to selecting an existing Azure VNet/Subnet, as the VM / Network Interface need to be in the same Azure Location that the existing VNet is already deployed.

**Comment by rsanderson2350** [comment]
Confirmed.  ARM objects (specifically the VNets needed here) have not been queried upon new target subscription selection.  Reviewing code for fix.

**Comment by rsanderson2350** [comment]
v2.4.2.1 is now available, should be resolved.  Please verify/advised.

**Comment by ManuInNZ** [comment]
Still have issues with new VNet/subnet creation
Although I can create a new VNet, which is then available for selection on the NIC, I can't fully create a subnet and therefore have it available in the dropdown for the NIC.
This basically makes the NIC invalid and generates 2 errors that prevents output generation.

Context: latest migAZ i.e. today's ( v2.4.2.1 ) doing an ASM to ARM migration of a classic cloud service

**Comment by rsanderson2350** [comment]
The issue discussed / resolved in this thread was the binding of a NIC to an existing Azure VNet/Subnet (within the target subscription).  The problem resolved in the recent build addresses that the Target Subscription "existing VMs" were not loaded into the existing cache, thus not available.  That has been resolved.

For your scenario, I believe you are using the MigAz tool to "create a new VNet and Subnet in the migration".  The user controls have not been built out far enough yet for you to "add a new Subnet" fully into the tool.  You can add a new Virtual Network, and add a new Subnet; however, the property editors do not have the ability yet to define the CIDR of the subnet.  This is expected to come soon, but it is a more common scenario that you would already have an existing Virtual Network + Subnet that you are need to migrate / clone your Azure Virtual Machine into.  You should look to build your VNet/Subnet natively within Azure, and then target that VNet/Subnet in a migration scenario.  As mentioned, subnet CIDR editing should be available soon in the tool; however, recommendation remains that this is not expected to be a primary function (as the VNet/Subnet commonly already exist in most migration scenarios.

**Comment by ManuInNZ** [comment]
Thank you
Sounds fair

**Comment by BorisChomette** [comment]
Picking up a existing VNET is working. So for me it's "problem solved"
